# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comunicacion.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63omunicacion.proto\x12\x0e\x63omunicaciones\"\x07\n\x05\x45mpty\"*\n\x06Status\x12\x14\n\x07success\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\n\n\x08_success\"L\n\x08\x45lemento\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65scripcion\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x05\n\x03_idB\x0e\n\x0c_descripcion\"=\n\x10ListadoElementos\x12)\n\x07objetos\x18\x01 \x03(\x0b\x32\x18.comunicaciones.Elemento2\xee\x01\n\x0b\x43omunicador\x12J\n\x13listador_elementos1\x12\x15.comunicaciones.Empty\x1a\x18.comunicaciones.Elemento\"\x00\x30\x01\x12P\n\x13listador_elementos2\x12\x15.comunicaciones.Empty\x1a .comunicaciones.ListadoElementos\"\x00\x12\x41\n\tagregador\x12\x18.comunicaciones.Elemento\x1a\x16.comunicaciones.Status\"\x00(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comunicacion_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=38
  _EMPTY._serialized_end=45
  _STATUS._serialized_start=47
  _STATUS._serialized_end=89
  _ELEMENTO._serialized_start=91
  _ELEMENTO._serialized_end=167
  _LISTADOELEMENTOS._serialized_start=169
  _LISTADOELEMENTOS._serialized_end=230
  _COMUNICADOR._serialized_start=233
  _COMUNICADOR._serialized_end=471
# @@protoc_insertion_point(module_scope)
